angular.module("myApp", [
        'schemaLoader',
        'lodash',
        'chieffancypants.loadingBar',
        'ui.bootstrap',
        'dashboard',
        'sync',
        'cgForm',
        'cgGrid',
        'appDefaultConfig',
        'appRoutes',
        'idService',
        'appService',
        'stateTransitions',
        'templates-app',
        'templates-common',
        'ui.router.state',
        'ui.router',
        'security',
        'report',
        'enum',
        'hc',
        'resamp',
        'ngcamera',
        'toaster']
    )
    .config(function ($stateProvider, $urlRouterProvider) {
        $urlRouterProvider.otherwise('/enum/area')
    })